project:
  type: website

website:
  title: "notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: flatly
      dark: slate
    css: styles.css
execute:
  freeze: auto
